name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: process_killer
  RUST_BACKTRACE: 1

permissions:
  contents: write

jobs:
  build-release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: process_killer-${{ github.ref_name }}-windows-x64.zip
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: process_killer-${{ github.ref_name }}-macos-x64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: process_killer-${{ github.ref_name }}-macos-arm64.tar.gz
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: process_killer-${{ github.ref_name }}-linux-x64.tar.gz
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 安装 Rust 工具链
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: 启用 Rust 缓存
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: 构建发布版本
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          
      - name: 打包构建产物
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.artifact_name }} process_killer.exe
          else
            tar -czf ../../../${{ matrix.artifact_name }} process_killer
          fi
          cd -

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./${{ matrix.artifact_name }}
          retention-days: 1

  publish-release:
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 下载构建产物
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./artifacts

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: ./artifacts/*
          body: |
            # Process Killer ${{ github.ref_name }}
            
            一个跨平台的进程终止工具。
            
            ## 支持平台
            - Windows (x64)
            - macOS (Intel x64)
            - macOS (Apple Silicon)
            - Linux (x64)
            
            ## 使用方法            ```bash
            process_killer <进程名>            ```
            
            ## 更新内容
            - 初始发布版本
            - 支持 Windows、macOS 和 Linux 平台
            - 支持通过进程名查找和终止进程